const age = "16";
console.log(age);
const name = "Alina";
console.log(name);
const isStudent = true;
console.log(isStudent);
const myString = "A person's freedom in the modern world is like the freedom of a person solving a crossword puzzle: theoretically, they can enter any word, although in reality they only have to enter one for the crossword puzzle to be solved.";
console.log(myString);
const number = 345;
const myNumber = number + 10;
console.log(myNumber);
const myNull = null;
console.log(myNull);
const userName = prompt("Введіть своє ім’я");
alert(userName);
console.log(typeof (userName));
const userAnswer = confirm("Ви дійсно хочете покинути сторінку?");
console.log(userAnswer);
const message = "Увага! Дія може бути небезпечною.";
const warning = confirm("Ви впевнені, що хочете продовжити?");
alert(message);

